export const COOKIES = [
  {
    id: 1,
    name: 'Chocolate Chip Cookies (12)',
    price: 7.50,
    description: 'One dozen Chocolate Chip Cookies. made with semi-sweet chocolate chips.',
    images: './images/products/chocolate-chip.jpg',
    category: 'Cookies',
  },
  {
    id: 2,
    name: 'Sugar Cookies (12)',
    price: 7.50,
    description: 'One dozen Sugar Cookies. Plain or can be made with your choice of colored sanding sugar on the outside.',
    images: './images/products/sugar-cookies.jpg',
    category: 'Cookies',
  },
  {
    id: 3,
    name: 'White Chocolate Macadamia Nut Cookies (12)',
    price: 7.50,
    description: 'One dozen White Chocolate Macadamia Nut Cookies.',
    images: './images/products/white-chocolate-macadamia.jpg',
    category: 'Cookies',
  },
  {
    id: 4,
    name: 'White Chocolate Macadamia Nut Cookies, with Cranberry (12)',
    price: 7.50,
    description: 'White Chocolate Macadamia Nut Cookies, with Cranberry (12)',
    images: './images/products/default_product.png',
    category: 'Cookies',
  },
  {
    id: 5,
    name: 'Snickerdoodle Cookies (12)',
    price: 7.50,
    description: 'One dozen Sugar Cookies rolled in cinnamon and sugar.',
    images: './images/products/default_product.png',
    category: 'Cookies',
  },
  {
    id: 6,
    name: 'Cinnamon Cookies (12)',
    price: 7.50,
    description: 'NEED A DESCRIPTION!!!.',
    images: './images/products/cinnamon-cookies.jpg',
    category: 'Cookies',
  },
  {
    id: 7,
    name: 'White Chocolate Chip Cookies (12)',
    price: 7.50,
    description: 'One dozen White Chocolate Chip Cookies.',
    images: './images/products/default_product.png',
    category: 'Cookies',
  },
  {
    id: 8,
    name: 'Pumpkin Spice Chip Cookies (12)',
    price: 7.50,
    description: 'One dozen Pumpkin Spice Chip Cookies. Like a chocolate chip cookie but with pumpkin spice chips.',
    images: './images/products/default_product.png',
    category: 'Cookies',
  },
  {
    id: 9,
    name: 'Peanut Butter Cookies (12)',
    price: 7.50,
    description: 'One dozen Pumpkin Spice Chip Cookies. Like a chocolate chip cookie but with pumpkin spice chips.',
    images: './images/products/default_product.png',
    category: 'Cookies',
  }
]